services:

  db:
    image: postgres:14
    restart: unless-stopped
    container_name: odoodb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  odooweb:
    image: odoo:16
    container_name: web_odoo
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8069"
      - "8072"
    environment:
      - USER=admin
      - PASSWORD=admin
      - HOST=db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
      
  nginx:
    build: 
      context: nginx     
    container_name: odoonginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - odooweb

volumes:
  pgdata:
  odoo-web-data:
